export const SAVE_PICTURES = 'SAVE_PICTURES';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SELECTED_PICTURE_TO_EDIT = 'SELECTED_PICTURE_TO_EDIT';
export const SAVE_CROPPED_IMAGE = 'SAVE_CROPPED_IMAGE';